version: 0.0

os: linux

files:
  - source: /
    destination: /tmp

hooks:
  ApplicationStart:
    - location: start.sh
      timeout: 180
      runas: root
  ApplicationStop:
    - location: stop.sh
      timeout: 180
      runas: root
