version: 0.0

os: linux

files:
  - source: /streaksaver-1.0.0.jar
    destination: /home/ec2-user/

hooks:
  ApplicationStart:
    - location: start.sh
      timeout: 180
      runas: root
  ApplicationStop:
    - location: stop.sh
      timeout: 180
      runas: root